name: Releases

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          token: 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
